### ISSUE TITLE
bad read performance when reading from EBS volumes

### ISSUE THREAD

**Issue by romange** [basho/leveldb#109]
Hi, 
I noticed that in basho/leveldb the mmap code in NewRandomAccessFile function is commented out. 

On amazon ec2 instances with ebs volumes attached the sequential reads on sstables are very slow when implemented using preads. 

I've created a small demo program that just reads an input sstable sequentially.

It reads 600MB sstable in 1m30s with preads (basho/leveldb) without the file being in file cache. 9s when the file is in machine file cache and 12s !!! when  NewRandomAccessFile is implemented via mmap as in the original leveldb while reading cold file again. The results are pretty consistent.

The io throughput is only 5-10MB with preads and around 80-100MB with mmap. This is due the fact that preads have non optimal read sizes when reading the sstable blocks.

I suggest returning the mmap code back to NewRandomAccessFile.

(I've run my tests on m1.medium instance with usual IOPS provisioning).

**Comment by matthewvon** [comment]
Where is the demo program?  I am curious how you manipulated the fadvise() calls in your test.

**Comment by romange** [comment]
The program listing is below.
What do you mean by manipulating fadvise calls? If you are referring to how I controlled whether the file was in file cache or not then I did it via command "echo 3 > /proc/sys/vm/drop_caches" (under root).

```
#include <iostream>

#include <leveldb/env.h>
#include <leveldb/options.h>
#include <leveldb/table.h>
int main(int argc, char **argv) {
    leveldb::RandomAccessFile* file = nullptr;
    uint64_t file_size = 0;
    auto status = leveldb::Env::Default()->GetFileSize(argv[i], &file_size);
    CHECK(status.ok()) << status.ToString();
    CHECK_GT(file_size, 0);
    status = leveldb::Env::Default()->NewRandomAccessFile(argv[i], &file);
    CHECK(status.ok()) << status.ToString();
    leveldb::Table* table = nullptr;
    status = leveldb::Table::Open(leveldb::Options(), file, file_size, &table);
    CHECK(status.ok()) << status.ToString();

    leveldb::ReadOptions read_opts;
    leveldb::Iterator* it = table->NewIterator(read_opts);

    for (it->SeekToFirst(); it->Valid(); it->Next()) {
      it->key();
      it->value();
      // cout << it->key().data() << ": " << it->value().size() << endl;
    }
    delete table;
    delete file;
  return 0;
}
```

**Comment by romange** [comment]
If you need a demo sst I can upload it as well.

**Comment by matthewvon** [comment]
I am not going to argue with your results.  I am running on a physical machine with 32G ram and a single SATA drive.  Test file is 183,210,264 bytes in size (because that is what I have sitting around).   I use Env::NowMicros() before the Table::Open() call and again just before the "delete table".  That measurement gives a consistent worst case of 2.47 seconds on both options when preceded by the drop_caches.  But the subsequent executions with "cache loaded" favor the non-mmap I/O.  It is typically 0.11 seconds.  The mmap fluctuates between 2.24 and 0.11 depending upon how fast I repeat the command.  This really feels like an environment specific issue.

**Comment by matthewvon** [comment]
I also moved the test file to a fusion IO card.  The worst case time for both is 0.487 seconds right after drop_caches.  After that, the pread is consistent with 0.104 seconds … and mmap fluctuates between 0.119 and 0.465.  I am willing to retry with your 600Mbyte file.  Still leaning toward this being environmental.

**Comment by romange** [comment]
Yes, I agree. I am pretty sure that preads on sata drives are more or less
as fast as mmap. But what's the downside to make leveldb fast on slower
drives like ebs?

**Comment by romange** [comment]
I do not think it's related to file but more to ebs speed. You run your
tests on fast drives with good response latency. Ebs drives are much slower
and probably have bigger latency impact for disk seeks.

**Comment by matthewvon** [comment]
The obvious reply is:  try and use what works best for you.  I lack experience with your environment.  My first concern is what happens when you have more data in your .sst files than logically fit inside your memory map, not physical memory but Intel logical address space.  I do not know, never been there.  Lowering your max_open_files setting if you see that becoming an issue might be the simple solution … I just do not know.

**Comment by matthewvon** [comment]
Additional note:  Recently reviewed another configuration where Riak 1.4 / 2.0 fadvise() logic was potentially counter productive.  The user's environment contained 200G Ram and only allocated less than 50% to leveldb (Riak 1.4).  This environment therefore had a huge chunk of memory available for Linux caching.  The DONT_NEED fadvise() calls against newly created .sst table files did flush the page cache.  And as expected, subsequent reads against those files would come from the disk.  However, the user has so much RAM that Riak 1.2 (without fadvise() changes) would actually perform the new reads from the page cache the majority of the time without harm to general disk throughput.  This environment, like @romange, would benefit from an option that disable the fadvise() logic.
