### ISSUE TITLE
Tiering LevelDB Levels for FS Record Size Optimization

### ISSUE THREAD

**Issue by wbrown** [basho/leveldb#126]
With the integration of dynamic block sizes into the tree, it provides a performance gain in many scenarios; however, it can be detrimental in the case of the ZFS filesystem.  I'd been studying the wiki page at: https://github.com/basho/leveldb/wiki/mv-dynamic-block-size -- thank you for this level of documentation, by the way.

ZFS has the ability to define record sizes at the ZVOL level.  It defaults to 128K.  If you write a sequence of 32x 4K blocks at once, it is going to end up in a 128K record.  Looking up any individual 4K block in that case is going to incur a read of the entire 128K block.

If you run ZFS, you are going to want to set a 4K block size for the youngest levels; but setting a 4K block size for a higher level file does not make sense, especially in the case of dynamic block sizes.

The current directory structure of LevelDB in Riak makes it extremely difficult to set the appropriate block sizes.  If the directory structure was in a predictable enough fashion and segmented by level, or block size, it makes it trivial to create individual ZVOLs for each level/block size.

Also, as it currently stands, the algorithm used for `block_size_steps` is not page aligned, making it difficult to avoid a double-read penalty when the block overlaps two records.  Additionally, if ZFS record sizes are larger than the LevelDB block size, we incur a read-modify-write penalty any time we write out a LevelDB block individually.

I realize that this proposed direction would be a drastic restructuring of the directory structure, but at the very least, if we could separate out level-0, it would greatly improve performance.

**Comment by matthewvon** [comment]
I suspect there is a leveldb concept that is unclear here.  "block_size" is not a fixed record length.  It is a threshold.  Leveldb continues to stuff full key/value pairs into a "block" until the value exceeds "block_size".  "Exceed" can be by one byte or five megabytes depending upon size of the most recent key/value pair.  Once "block_size" is exceeded, leveldb further adds the table of keys (restart points) to the block.  Finally, leveldb will attempt to compress the block.

The resulting disk size of any block can be larger or smaller than the "block_size".  The size and compressibility of your key/value pairs determines how close each block might actually be to "block_size".

Nothing in Google's logic attempts to get anything reasonably close to a page aligned structure.  So I agree that a random read has the potential to suffer your described double-read penalty.  However, leveldb is a write once database.  There are zero read-modify-write scenarios.  Writes are in 20 megabyte chunks, no matter how the logical "blocks" do or do not fit within that size.

**Comment by wbrown** [comment]
@matthewvon -- Thank you for the explanation.  This helped things click in my mind.  If writes are in 20MB chunks, no matter what the logical block size is -- that leads to my next question.  Are reads from a 20MB chunk done at the chunk level, i.e. loaded into memory and then accessed, or are they read from the disk at the block level -- i.e. `block_size` reads?

**Comment by matthewvon** [comment]
No.  Reads and writes are performed with two completely different technologies.  The technology selection is based upon performance tests with the variety of equipment available … and no, none of the performance tests used machines with ZFS.

Writes use memory mapped files.  The files are mapped into RAM in 20Mbyte chunks.  "Blocks" are written into the chunks.  A chunk is written to disk when it reaches its boundary, potentially splitting a Google "block" across multiple chunks.  Posix fadvise calls are used to suggest chunks that are best cached and chunks that should flush to disk now.

Read operations use pread().  Various experiments suggested that Linux is far more efficient at deciding what to cache in random scenarios.  This is why we use the pread() code instead of the memory mapped read code.  The pread() code requests the exact position and size of one compressed block.  We again use posix fadvise calls to tell Linux how each file will be used, random access or sequential read (for compactions).  The fadvise manipulations make a huge difference.

A read from disk is expensive:  compressed block read from disk, compressed block CRC checked, compressed block decompressed, and finally block's index scanned to locate key/value in block.  The decompression can take more time than the read on some really fast disk arrays and/or good operating system caching scenarios.  Therefore bigger blocks are not always more efficient from a random read scenario.

**Comment by wbrown** [comment]
Got it.  What I've been doing in my ZFS testing has been to enable ZFS compression with LZ4, which is actually better than the Snappy compression algorithm used by LevelDB.  I've also disabled the Snappy compression in LevelDB in this case.

So, with Snappy compressed, the 'on-disk' representation is whatever the block size is.  ZFS takes care of the compression behind the scenes.  By default, ZFS uses a 128K record size -- if writes are done in 20MB chunks, this would be turned into 160 128K blocks laid down as a single transaction.  The dark side of this is, when LevelDB requests a block from the filesystem layer, it is going to be a single 128K block.  On the other hand, the percentage of double-reads of a 128K block is going to be lower.  When a double-read happens, then it's going to be 256K of reads.

The question then becomes, how random is a random lookup? What is the likelihood that if you read a LevelDB block, that you're going to be reading the neighboring blocks?  If it's pretty high, then a larger ZVOL record size might be beneficial.  If it's low, a smaller ZVOL record size would benefit in the read case, but not the write case.

**Comment by matthewvon** [comment]
Is this issue resolved?
