### ISSUE TITLE
replace gettimeofday() with sliding counter in LRUCache::Lookup

### ISSUE THREAD

**Issue by matthewvon** [basho/leveldb#25]
I hammered gettimeofday() into LRUCache::Lookup in place of the previous mechanism that constantly reordered the list, requiring a write lock.  gettimeofday() is a relatively expensive OS call.  A better design would use an incrementing counter.  When the counter crossed a threshold, all instances of the counter would be right shifted 32 bits.

**Comment by bergwolf** [comment]
Not really for Linux at least. Linux kernel optimizes for gettimeofday() by sharing kernel page (vsyscall or vdso) with user apps so that some functions like gettimeofday() don't need to change to kernel mode. It works faster than an atomic counter (if that is what you are proposing...) especially on multi-core machines.

**Comment by matthewvon** [comment]
addressed in post Riak 1.4 code
